### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by izackwu** [suziwen/gatsby-plugin-gitalk#3]
Seems that Gitalk has a major update and this plugin fails to work now.

See https://github.com/gitalk/gitalk/issues/429

**Comment by suziwen** [comment]
You can custom proxy like this:
``` javascript 
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-gitalk`,
      options: {
        config: {
            ....
            proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token',
            ....
          }
      }
    },
  ]
}
```

**Comment by izackwu** [comment]
@suziwen Yeah, I know that. But I think it's better to change the default proxy in the next version, making it easier for new users.

**Comment by suziwen** [comment]
Thanks for your suggestion, the latest version has been patched.
