### ISSUE TITLE
Support for React v17

### ISSUE THREAD

**Issue by Vacilando** [suziwen/gatsby-plugin-gitalk#5]
This plugin is still dependent on React 16.8.5 while Gatsby needs React 16.9.0 at the minimum since v3 (cf https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#react-17), and React 17 is also fully supported.

Could the dependency be updated to React 16.9.0 or ideally React 17?

**Comment by suziwen** [comment]
You can ignore the warning, this version is still compatible with React 17.
Or you can upgrade to v1.2.6, I modified their dependencies today.

**Comment by Vacilando** [comment]
Excellent, thanks!
